/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_better_Framework */

#ifndef _Included_com_example_demo_better_Framework
#define _Included_com_example_demo_better_Framework
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_better_Framework
 * Method:    whl
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_demo_better_Framework_whl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_demo_better_Framework
 * Method:    create
 * Signature: ()Lcom/example/demo/domain/Camera;
 */
JNIEXPORT jobject JNICALL Java_com_example_demo_better_Framework_create
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
